// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { GridConfig, GridConfigTableId } from "./tables/GridConfig.sol";
import { RoomMap, RoomMapTableId } from "./tables/RoomMap.sol";
import { Disabled, DisabledTableId } from "./tables/Disabled.sol";
import { IsMine, IsMineTableId } from "./tables/IsMine.sol";
import { IsMarked, IsMarkedTableId } from "./tables/IsMarked.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
import { MineCount, MineCountTableId } from "./tables/MineCount.sol";
import { Points, PointsTableId } from "./tables/Points.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
