// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { GridConfig, GridConfigTableId } from "./tables/GridConfig.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { Disabled, DisabledTableId } from "./tables/Disabled.sol";
import { IsMine, IsMineTableId } from "./tables/IsMine.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
