// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IPlayerSystem {
  function click(bytes32 roomId, uint32 x, uint32 y) external;

  function mark(bytes32 roomId, uint32 x, uint32 y) external;

  function placeMine(bytes32 roomId, uint32 x, uint32 y) external;

  function purchase() external;

  function lose(bytes32 player) external;

  function expand(
    bytes32 roomId,
    bytes32 player,
    uint32 x,
    uint32 y,
    uint32 width,
    uint32 height,
    uint32 expandCount
  ) external;

  function clear(bytes32 roomId, uint32 x, uint32 y, uint32 width, uint32 height) external;

  function countMines(bytes32 roomId, uint32 x, uint32 y, uint32 width, uint32 height) external view returns (uint32);
}
